### PR TITLE
Fix network interface names

### LINKED ISSUE #122: After HA event nics get mixed up on virtual routers
After an HA event, nics on the virtual router get mixed up in case a tier was removed and readded (or a private gw). This is most likely caused by the fact that the nics are plugged in the order in which they appear in the database. The device_id seems not to be taken in consideration, or it is not sorted by device id (or something like that).

See comments for simple scenario / steps to reproduce.

### PR DESCRIPTION
**Pull request by bheuvel**
Closes #122

### CODE REVIEW

**Comment by remibergsma** [comment]
Did we run tests against this? I see many issues where nics get weird names and stuff doesn't work as a result. It's either this PR or the systemvm template that I used (packer one, worked fine before and is also in prod).

See this:

```
May 21 12:26:18 r-12-VM udevd[291]: GOTO 'persistent_net_generator_end' has no matching label in: '/etc/udev/rules.d/75-persistent-net-generator.rules'
May 21 12:27:53 r-12-VM udevd[2433]: error changing net interface name rename3 to eth0: File exists
May 21 12:27:53 r-12-VM udevd[291]: GOTO 'persistent_net_generator_end' has no matching label in: '/etc/udev/rules.d/75-persistent-net-generator.rules'
May 21 12:27:53 r-12-VM udevd[291]: GOTO 'persistent_net_generator_end' has no matching label in: '/etc/udev/rules.d/75-persistent-net-generator.rules'
```
weird-dev-names

So public nic eth1 on VPC didn't work. The rules look like this:

```
root@r-14-VM:~# cat /etc/udev/rules.d/70-persistent-net.rules 
# This file was automatically generated by the /lib/udev/write_net_rules
# program, run by the persistent-net-generator.rules rules file.
#
# You can modify it, as long as you keep each rule on a single
# line, and change only the value of the NAME= key.

# PCI device 0x1af4:/sys/devices/pci0000:00/0000:00:03.0/virtio0 (virtio_net)
SUBSYSTEM=="net", ACTION=="add", ATTR{dev_id}=="0x0", ATTR{type}=="1", KERNEL=="eth*", NAME="eth0"

# PCI device 0x1af4:/sys/devices/pci0000:00/0000:00:06.0/virtio3 (virtio_net)
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="06:06:34:00:00:1a", ATTR{dev_id}=="0x0", ATTR{type}=="1", KERNEL=="eth*", NAME="eth1"
```
So that looks quite OK, but the device wasn't named like this. I decided to reboot from cmd line and then it became a real mess:

```
iroot@r-14-VM:~# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 16436 qdisc noqueue state UNKNOWN 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
2: eth3: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN qlen 1000
    link/ether 0e:00:a9:fe:02:e1 brd ff:ff:ff:ff:ff:ff
3: eth2: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN qlen 1000
    link/ether 06:06:34:00:00:1a brd ff:ff:ff:ff:ff:ff
root@r-14-VM:~# cat /etc/udev/rules.d/70-persistent-net.rules 
# This file was automatically generated by the /lib/udev/write_net_rules
# program, run by the persistent-net-generator.rules rules file.
#
# You can modify it, as long as you keep each rule on a single
# line, and change only the value of the NAME= key.

# PCI device 0x1af4:/sys/devices/pci0000:00/0000:00:03.0/virtio0 (virtio_net)
SUBSYSTEM=="net", ACTION=="add", ATTR{dev_id}=="0x0", ATTR{type}=="1", KERNEL=="eth*", NAME="eth0"

# PCI device 0x1af4:/sys/devices/pci0000:00/0000:00:06.0/virtio3 (virtio_net)
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="06:06:34:00:00:1a", ATTR{dev_id}=="0x0", ATTR{type}=="1", KERNEL=="eth*", NAME="eth1"

# PCI device 0x1af4:/sys/devices/pci0000:00/0000:00:06.0/virtio3 (virtio_net)
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="06:06:34:00:00:1a", ATTR{dev_id}=="0x0", ATTR{type}=="1", KERNEL=="rename*", NAME="rename3"

# PCI device 0x1af4:/sys/devices/pci0000:00/0000:00:06.0/virtio3 (virtio_net)
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="06:06:34:00:00:1a", ATTR{dev_id}=="0x0", ATTR{type}=="1", KERNEL=="eth*", NAME="eth2"

# PCI device 0x1af4:/sys/devices/pci0000:00/0000:00:03.0/virtio0 (virtio_net)
SUBSYSTEM=="net", ACTION=="add", ATTR{dev_id}=="0x0", ATTR{type}=="1", KERNEL=="eth*", NAME="eth3"

# PCI device 0x1af4:/sys/devices/pci0000:00/0000:00:06.0/virtio3 (virtio_net)
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="06:06:34:00:00:1a", ATTR{dev_id}=="0x0", ATTR{type}=="1", KERNEL=="eth*", NAME="eth4"

# PCI device 0x1af4:/sys/devices/pci0000:00/0000:00:03.0/virtio0 (virtio_net)
SUBSYSTEM=="net", ACTION=="add", ATTR{dev_id}=="0x0", ATTR{type}=="1", KERNEL=="eth*", NAME="eth5"
root@r-14-VM:~# 
```

On another router, same begin situation with the 'rename3 device'. Then added a tier:

```
root@r-12-VM:/etc/udev/rules.d# cat 70-persistent-net.rules 
# This file was automatically generated by the /lib/udev/write_net_rules
# program, run by the persistent-net-generator.rules rules file.
#
# You can modify it, as long as you keep each rule on a single
# line, and change only the value of the NAME= key.

# PCI device 0x1af4:/sys/devices/pci0000:00/0000:00:03.0/virtio0 (virtio_net)
SUBSYSTEM=="net", ACTION=="add", ATTR{dev_id}=="0x0", ATTR{type}=="1", KERNEL=="eth*", NAME="eth0"

# PCI device 0x1af4:/sys/devices/pci0000:00/0000:00:06.0/virtio3 (virtio_net)
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="06:9b:e8:00:00:19", ATTR{dev_id}=="0x0", ATTR{type}=="1", KERNEL=="eth*", NAME="eth1"

# PCI device 0x1af4:/sys/devices/pci0000:00/0000:00:06.0/virtio3 (virtio_net)
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="06:9b:e8:00:00:19", ATTR{dev_id}=="0x0", ATTR{type}=="1", KERNEL=="rename*", NAME="rename3"

# PCI device 0x1af4:/sys/devices/pci0000:00/0000:00:07.0/virtio4 (virtio_net)
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="02:00:72:66:00:02", ATTR{dev_id}=="0x0", ATTR{type}=="1", KERNEL=="eth*", NAME="eth2"

# PCI device 0x1af4:/sys/devices/pci0000:00/0000:00:07.0/virtio4 (virtio_net)
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="02:00:72:66:00:02", ATTR{dev_id}=="0x0", ATTR{type}=="1", KERNEL=="eth*", NAME="eth3"
root@r-12-VM:/etc/udev/rules.d# 
```

Two interfaces were reserved for the same mac address. Obviously, this gets out-of-sync.

Ping @borisroman @bheuvel

**Comment by remibergsma** [comment]
Jenkins tests results: https://beta-jenkins.mcc.schubergphilis.com/job/cosmic/job/0002-tracking-repo-branch-build/93/
Also many errors.

**Comment by remibergsma** [comment]
The jenkins tests were done with the old template.

**Comment by bheuvel** [comment]
@remi, @borisroman, sorry, stupid commit mistake...but I can confirm this commit breaks stuff that works.

Created a new branch/same name with the correct commit (differs by one `"`). Running `run_marvin_router_tests.sh` in the bubble now, and it doesn't fail immediately.... :blush:

**Pull request merged**
