### PR TITLE
Fix rVPC multi tiers test

### PR DESCRIPTION
**Pull request by wilderrodrigues**
Before checking the Master router, we are now sleeping 5 seconds because since we are removing the first tier (NIC) the VRRP will have to reconfigure the interface it uses. Due to the configuration changes, it will start a new election and it might take up to 4 seconds, because each router has an advertisement interval of 2 seconds.

In the 2nd check, we have to sleep 2 seconds (adv interval) because removing an interface will trigger VRRP.

In my opinion, It has to be fixed because an interface not configured on keepalived should not do such a thing. Will create a separate PR to cover that.

### CODE REVIEW

**Comment by wilderrodrigues** [comment]
Ping @remibergsma @bheuvel @miguelaferreira 

```
[root@cs1 integration]# less /tmp//MarvinLogs/test_vpc_redundant_0CBJGV/results.txt 
Create a redundant VPC with 3 Tiers, 3 VMs, 3 PF rules ... === TestName: test_05_rvpc_multi_tiers | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 1 test in 1010.213s

OK
/tmp//MarvinLogs/test_vpc_redundant_0CBJGV/results.txt (END)
```

**Comment by wilderrodrigues** [comment]
Lats results.

```
[root@cs1 integration]# less /tmp//MarvinLogs/test_vpc_redundant_NONH4J/results.txt 
Create a redundant VPC with 3 Tiers, 3 VMs, 3 PF rules ... === TestName: test_05_rvpc_multi_tiers | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 1 test in 962.902s

OK
/tmp//MarvinLogs/test_vpc_redundant_NONH4J/results.txt (END)
```

**Comment by wilderrodrigues** [comment]
Build running here: https://beta-jenkins.mcc.schubergphilis.com/job/cosmic/job/0020-tracking-repo-build/67/

**Comment by miguelaferreira** [comment]
Waiting for full build to finish

**Comment by wilderrodrigues** [comment]
Only Net GC is failing. But that we already now and is the one I'm now taking care of. Let's wait for Jenkins :)

```
Create a redundant VPC with two networks with two VMs in each network ... === TestName: test_01_create_redundant_VPC_2tiers_4VMs_4IPs_4PF_ACL | Status : SUCCESS ===
ok
Create a redundant VPC with two networks with two VMs in each network and check default routes ... === TestName: test_02_redundant_VPC_default_routes | Status : SUCCESS ===
ok
Create a redundant VPC with two networks with two VMs in each network ... === TestName: test_03_create_redundant_VPC_1tier_2VMs_2IPs_2PF_ACL_reboot_routers | Status : SUCCESS ===
ok
Create a redundant VPC with 1 Tier, 1 VM, 1 ACL, 1 PF and test Network GC Nics ... === TestName: test_04_rvpc_network_garbage_collector_nics | Status : FAILED ===
FAIL
Create a redundant VPC with 3 Tiers, 3 VMs, 3 PF rules ... === TestName: test_05_rvpc_multi_tiers | Status : SUCCESS ===
ok

======================================================================
FAIL: Create a redundant VPC with 1 Tier, 1 VM, 1 ACL, 1 PF and test Network GC Nics
----------------------------------------------------------------------
```

**Comment by wilderrodrigues** [comment]
Ping @miguelaferreira @remibergsma @bheuvel @borisroman 

Build is fine and tests passed. We still have the failing ones that were already fixed but not included in this PR.

Could one of you please merge it? :)

Cheers,
Wilder

**Pull request merged**
