### PR TITLE
Remove cloud-cli folder

### PR DESCRIPTION
**Pull request by borisroman**
Ping @remibergsma @wilderrodrigues

### CODE REVIEW

**Comment by remibergsma** [comment]
As discussed: check packaging ;-)

**Comment by wilderrodrigues** [comment]
Was this CLI used only for volume management?

**Comment by borisroman** [comment]
@wilderrodrigues This was the pre-cloudmonkey cli.

**Comment by borisroman** [comment]
@remibergsma Packaging already checked: https://github.com/MissionCriticalCloud/cosmic/pull/16

**Comment by wilderrodrigues** [comment]
Did you created the RPMs as well, @borisroman ? Just for the sake of it. :)

**Comment by borisroman** [comment]
RPM builds
```
+ exit 0
RPM Build Done
```

**Comment by wilderrodrigues** [comment]
LGTM

**Pull request merged**
