### PR TITLE
Applies the commits from MCCloud to Cosmic

### PR DESCRIPTION
**Pull request by wilderrodrigues**
This PR contains all the commits from MCCloud  that were related to fixing the virtual routers and some UI improvements.

### CODE REVIEW

**Comment by wilderrodrigues** [comment]
go build

**Comment by miguelaferreira** [comment]
I've built this PR by pulling the code into a [cosmic build](https://beta-jenkins.mcc.schubergphilis.com/job/cosmic-dev/job/tracking-repo-custom-branch-build/7/)

The build did not run the "complete" marvin test suite. It ran

* with hardware:
  * smoke/test_password_server.py
  * smoke/test_vpc_redundant.py
* without hardware
  * smoke/test_routers.py
  * smoke/test_network_acl.py

**Comment by borisroman** [comment]
Running the full suite now:

https://beta-jenkins.mcc.schubergphilis.com/job/cosmic/job/tracking-repo-build/3/

**Comment by remibergsma** [comment]
@wilderrodrigues Nice for taking care of this! You'd do me a favour when you'd reword e8a71ea... was a bit frustrated at the time I guess. Sorry! ;-)

**Comment by wilderrodrigues** [comment]
ping @borisroman 

How about this PR, and others related, getting some more attention? Should we get the build running against it again?

Cheers,
Wilder

**Comment by wilderrodrigues** [comment]
Ping @miguelaferreira @borisroman @remibergsma 

This PR now contains all the commits we have added to MCCloud master.

* Full Cosmic build

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10:00 min
[INFO] Finished at: 2016-03-07T15:59:37+01:00
[INFO] Final Memory: 95M/1234M
[INFO] ------------------------------------------------------------------------
```

I will proceed with the integration tests.

**Comment by wilderrodrigues** [comment]
Only the cosmic-core build is also fine.

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 08:31 min
[INFO] Finished at: 2016-03-07T16:57:57+01:00
[INFO] Final Memory: 70M/689M
[INFO] ------------------------------------------------------------------------
sbpltk1zffh04:cosmic-core wrodrigues$ 
```

**Comment by wilderrodrigues** [comment]
Ping @remibergsma @miguelaferreira @borisroman 

* Tests with Hardware:

 - 2 Failures due to wget www.google.com
  - AssertionError: Attempt to retrieve google.com index page should be successful once rule is added!
 - 1 Failure that looks like a false positive, probably due to sleeps in the code. It expected 2 routers in the BACKUP state, but found only one. So, a router came back as MASTER quite quickly
   - AssertionError: Expected '2' routers at state 'BACKUP', but found '1'

```
Test redundant router internals ... === TestName: test_01_isolate_network_FW_PF_default_routes_egress_true | Status : SUCCESS ===
ok
Test redundant router internals ... === TestName: test_02_isolate_network_FW_PF_default_routes_egress_false | Status : SUCCESS ===
ok
Test redundant router internals ... === TestName: test_01_RVR_Network_FW_PF_SSH_default_routes_egress_true | Status : FAILED ===
FAIL
Test redundant router internals ... === TestName: test_02_RVR_Network_FW_PF_SSH_default_routes_egress_false | Status : FAILED ===
FAIL
Test redundant router internals ... === TestName: test_03_RVR_Network_check_router_state | Status : SUCCESS ===
ok
Create a redundant VPC with two networks with two VMs in each network ... === TestName: test_01_create_redundant_VPC_2tiers_4VMs_4IPs_4PF_ACL | Status : SUCCESS ===
ok
Create a redundant VPC with two networks with two VMs in each network and check default routes ... === TestName: test_02_redundant_VPC_default_routes | Status : SUCCESS ===
ok
Create a redundant VPC with two networks with two VMs in each network ... === TestName: test_03_create_redundant_VPC_1tier_2VMs_2IPs_2PF_ACL_reboot_routers | Status : SUCCESS ===
ok
Create a redundant VPC with 1 Tier, 1 VM, 1 ACL, 1 PF and test Network GC Nics ... === TestName: test_04_rvpc_network_garbage_collector_nics | Status : FAILED ===
FAIL
Create a redundant VPC with 1 Tier, 1 VM, 1 ACL, 1 PF and test Network GC Nics ... === TestName: test_05_rvpc_multi_tiers | Status : SUCCESS ===
ok
Test iptables default INPUT/FORWARD policy on RouterVM ... === TestName: test_02_routervm_iptables_policies | Status : SUCCESS ===
ok
Test iptables default INPUT/FORWARD policies on VPC router ... === TestName: test_01_single_VPC_iptables_policies | Status : SUCCESS ===
ok
Create a VPC with two networks with one VM in each network and test nics after destroy ... === TestName: test_01_VPC_nics_after_destroy | Status : SUCCESS ===
ok
Create a VPC with two networks with one VM in each network and test default routes ... === TestName: test_02_VPC_default_routes | Status : SUCCESS ===
ok
Check the password file in the Router VM ... === TestName: test_isolate_network_password_server | Status : SUCCESS ===
ok
Check that the /etc/dhcphosts.txt doesn't contain duplicate IPs ... === TestName: test_router_dhcphosts | Status : SUCCESS ===
ok
Test to create Load balancing rule with source NAT ... === TestName: test_01_create_lb_rule_src_nat | Status : SUCCESS ===
ok
Test to create Load balancing rule with non source NAT ... === TestName: test_02_create_lb_rule_non_nat | Status : SUCCESS ===
ok
Test for assign & removing load balancing rule ... === TestName: test_assign_and_removal_lb | Status : SUCCESS ===
ok
Test create, assign, remove of an Internal LB with roundrobin http traffic to 3 vm's in a Single VPC ... === TestName: test_01_internallb_roundrobin_1VPC_3VM_HTTP_port80 | Status : SUCCESS ===
ok
Test create, assign, remove of an Internal LB with roundrobin http traffic to 3 vm's in a Redundant VPC ... === TestName: test_02_internallb_roundrobin_1RVPC_3VM_HTTP_port80 | Status : SUCCESS ===
ok
Test to verify access to loadbalancer haproxy admin stats page ... === TestName: test_03_vpc_internallb_haproxy_stats_on_all_interfaces | Status : SUCCESS ===
ok
Test to verify access to loadbalancer haproxy admin stats page ... === TestName: test_04_rvpc_internallb_haproxy_stats_on_all_interfaces | Status : SUCCESS ===
ok
Test SSVM Internals ... === TestName: test_03_ssvm_internals | Status : SUCCESS ===
ok
Test CPVM Internals ... === TestName: test_04_cpvm_internals | Status : SUCCESS ===
ok
Test stop SSVM ... === TestName: test_05_stop_ssvm | Status : SUCCESS ===
ok
Test stop CPVM ... === TestName: test_06_stop_cpvm | Status : SUCCESS ===
ok
Test reboot SSVM ... === TestName: test_07_reboot_ssvm | Status : SUCCESS ===
ok
Test reboot CPVM ... === TestName: test_08_reboot_cpvm | Status : SUCCESS ===
ok
Test destroy SSVM ... === TestName: test_09_destroy_ssvm | Status : SUCCESS ===
ok
Test destroy CPVM ... === TestName: test_10_destroy_cpvm | Status : SUCCESS ===
ok
Test Site 2 Site VPN Across redundant VPCs ... === TestName: test_01_redundant_vpc_site2site_vpn | Status : SUCCESS ===
ok
Test Remote Access VPN in VPC ... === TestName: test_01_vpc_remote_access_vpn | Status : SUCCESS ===
ok
Test Site 2 Site VPN Across VPCs ... === TestName: test_01_vpc_site2site_vpn | Status : SUCCESS ===
ok
Test for port forwarding on source NAT ... === TestName: test_01_port_fwd_on_src_nat | Status : SUCCESS ===
ok
Test for port forwarding on non source NAT ... === TestName: test_02_port_fwd_on_non_src_nat | Status : SUCCESS ===
ok
Test for reboot router ... === TestName: test_reboot_router | Status : SUCCESS ===
ok
Test for Router rules for network rules on acquired public IP ... === TestName: test_network_rules_acquired_public_ip_1_static_nat_rule | Status : SUCCESS ===
ok
Test for Router rules for network rules on acquired public IP ... === TestName: test_network_rules_acquired_public_ip_2_nat_rule | Status : SUCCESS ===
ok
Test for Router rules for network rules on acquired public IP ... === TestName: test_network_rules_acquired_public_ip_3_Load_Balancer_Rule | Status : SUCCESS ===
ok


----------------------------------------------------------------------
Ran 40 tests in 18515.370s

FAILED (failures=3)
```

**Comment by wilderrodrigues** [comment]
Private gateways tests with VLAN

* rVPC + 1 Tier + 1 ACL + 1 VM + 1 Pub IP + 1 PF + 1 Private GW

* Master router
```
root@r-143-VM:~# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 16436 qdisc noqueue state UNKNOWN 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 0e:00:a9:fe:03:2b brd ff:ff:ff:ff:ff:ff
    inet 169.254.3.43/16 brd 169.254.255.255 scope global eth0
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 06:03:e0:00:00:2d brd ff:ff:ff:ff:ff:ff
    inet 192.168.23.55/24 brd 192.168.23.255 scope global eth1
    inet 192.168.23.56/24 brd 192.168.23.255 scope global secondary eth1
4: eth2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 02:00:7b:d1:00:02 brd ff:ff:ff:ff:ff:ff
    inet 10.0.1.60/24 brd 10.0.1.255 scope global eth2
    inet 10.0.1.1/24 brd 10.0.1.255 scope global secondary eth2
5: eth3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 06:b7:a6:00:00:66 brd ff:ff:ff:ff:ff:ff
    inet 192.168.23.100/24 brd 192.168.23.255 scope global eth3
root@r-143-VM:~# 
```

* Backup router
```
root@r-144-VM:~# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 16436 qdisc noqueue state UNKNOWN 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 0e:00:a9:fe:03:7a brd ff:ff:ff:ff:ff:ff
    inet 169.254.3.122/16 brd 169.254.255.255 scope global eth0
3: eth1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN qlen 1000
    link/ether 06:03:e0:00:00:2d brd ff:ff:ff:ff:ff:ff
    inet 192.168.23.55/24 brd 192.168.23.255 scope global eth1
    inet 192.168.23.56/24 brd 192.168.23.255 scope global secondary eth1
4: eth2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 02:00:3a:6b:00:03 brd ff:ff:ff:ff:ff:ff
    inet 10.0.1.138/24 brd 10.0.1.255 scope global eth2
5: eth3: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN qlen 1000
    link/ether 06:96:22:00:00:66 brd ff:ff:ff:ff:ff:ff
    inet 192.168.23.100/24 brd 192.168.23.255 scope global eth3
root@r-144-VM:~#
``

* Stop Master router
  - New Master router
```
root@r-144-VM:~# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 16436 qdisc noqueue state UNKNOWN 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 0e:00:a9:fe:03:7a brd ff:ff:ff:ff:ff:ff
    inet 169.254.3.122/16 brd 169.254.255.255 scope global eth0
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 06:03:e0:00:00:2d brd ff:ff:ff:ff:ff:ff
    inet 192.168.23.55/24 brd 192.168.23.255 scope global eth1
    inet 192.168.23.56/24 brd 192.168.23.255 scope global secondary eth1
4: eth2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 02:00:3a:6b:00:03 brd ff:ff:ff:ff:ff:ff
    inet 10.0.1.138/24 brd 10.0.1.255 scope global eth2
    inet 10.0.1.1/24 brd 10.0.1.255 scope global secondary eth2
5: eth3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 06:96:22:00:00:66 brd ff:ff:ff:ff:ff:ff
    inet 192.168.23.100/24 brd 192.168.23.255 scope global eth3
root@r-144-VM:~#
```

* Start stopped router
  - New Backup router
```
root@r-143-VM:~# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 16436 qdisc noqueue state UNKNOWN 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 0e:00:a9:fe:01:ba brd ff:ff:ff:ff:ff:ff
    inet 169.254.1.186/16 brd 169.254.255.255 scope global eth0
3: eth1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN qlen 1000
    link/ether 06:03:e0:00:00:2d brd ff:ff:ff:ff:ff:ff
    inet 192.168.23.56/24 brd 192.168.23.255 scope global eth1
    inet 192.168.23.55/24 brd 192.168.23.255 scope global secondary eth1
4: eth2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 02:00:7b:d1:00:02 brd ff:ff:ff:ff:ff:ff
    inet 10.0.1.60/24 brd 10.0.1.255 scope global eth2
5: eth3: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN qlen 1000
    link/ether 06:b7:a6:00:00:66 brd ff:ff:ff:ff:ff:ff
root@r-143-VM:~#
```

* Fail back
  - New Master router
```
root@r-143-VM:~# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 16436 qdisc noqueue state UNKNOWN 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 0e:00:a9:fe:01:ba brd ff:ff:ff:ff:ff:ff
    inet 169.254.1.186/16 brd 169.254.255.255 scope global eth0
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 06:03:e0:00:00:2d brd ff:ff:ff:ff:ff:ff
    inet 192.168.23.56/24 brd 192.168.23.255 scope global eth1
    inet 192.168.23.55/24 brd 192.168.23.255 scope global secondary eth1
4: eth2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 02:00:7b:d1:00:02 brd ff:ff:ff:ff:ff:ff
    inet 10.0.1.60/24 brd 10.0.1.255 scope global eth2
    inet 10.0.1.1/24 brd 10.0.1.255 scope global secondary eth2
5: eth3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 06:b7:a6:00:00:66 brd ff:ff:ff:ff:ff:ff
root@r-143-VM:~#
```

Problems:

1. IP not in the new Backup router and also not in the new Master router.
2. Restart VPC with clean-up is broken

```
2016-03-08 10:40:07,031 WARN  [c.c.n.r.VpcVirtualNetworkApplianceManagerImpl] (Work-Job-Executor-4:ctx-1f85f4d9 job-1303/job-1307 ctx-5f20aeef) (logid:6a087cee) Failed to add router VM[
DomainRouter|r-149-VM] to network due to exception 
java.lang.NullPointerException
        at com.cloud.network.NetworkModelImpl.getNetworkRate(NetworkModelImpl.java:994)
        at com.cloud.network.router.VpcVirtualNetworkApplianceManagerImpl.finalizeCommandsOnStart(VpcVirtualNetworkApplianceManagerImpl.java:384)
        at com.cloud.network.router.VirtualNetworkApplianceManagerImpl.finalizeDeployment(VirtualNetworkApplianceManagerImpl.java:1666)
        at com.cloud.vm.VirtualMachineManagerImpl.orchestrateStart(VirtualMachineManagerImpl.java:1017)
        at com.cloud.vm.VirtualMachineManagerImpl.orchestrateStart(VirtualMachineManagerImpl.java:4580)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.cloud.vm.VmWorkJobHandlerProxy.handleVmWorkJob(VmWorkJobHandlerProxy.java:107)
        at com.cloud.vm.VirtualMachineManagerImpl.handleVmWorkJob(VirtualMachineManagerImpl.java:4741)
        at com.cloud.vm.VmWorkJobDispatcher.runJob(VmWorkJobDispatcher.java:102)
        at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.runInContext(AsyncJobManagerImpl.java:554)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:56)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:103)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:53)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
        at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.run(AsyncJobManagerImpl.java:502)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

Will investigate.

**Comment by wilderrodrigues** [comment]
Found the toot cause. We now create a NicProfile in order to send the profile to the ```_commandSetupHelper.createVpcAssociatePrivateIPCommands(domainRouterVO, privateIps, cmds, privateNicProfile, true);```

It fails on the following call:

```
                        NicProfile privateNicProfile =
                            new NicProfile(guestNic, network, network.getBroadcastUri(), network.getBroadcastUri(), _networkModel.getNetworkRate(
                                guestNic.getId(), domainRouterVO.getId()), _networkModel.isSecurityGroupSupportedInNetwork(network), _networkModel.getNetworkTag(
                                    domainRouterVO.getHypervisorType(), network));
```

**Comment by wilderrodrigues** [comment]
Bug fixed!

Tests with VLAN. I will now test with NSX.

* Restart rVPC with clean-up
  - New Master router
```
root@r-152-VM:~# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 16436 qdisc noqueue state UNKNOWN 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 0e:00:a9:fe:00:ad brd ff:ff:ff:ff:ff:ff
    inet 169.254.0.173/16 brd 169.254.255.255 scope global eth0
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 06:3b:ac:00:00:2d brd ff:ff:ff:ff:ff:ff
    inet 192.168.23.55/24 brd 192.168.23.255 scope global eth1
    inet 192.168.23.56/24 brd 192.168.23.255 scope global secondary eth1
4: eth2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 06:ad:f6:00:00:66 brd ff:ff:ff:ff:ff:ff
    inet 192.168.23.100/24 brd 192.168.23.255 scope global eth2
5: eth3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 02:00:61:08:00:0a brd ff:ff:ff:ff:ff:ff
    inet 10.0.1.233/24 brd 10.0.1.255 scope global eth3
    inet 10.0.1.1/24 brd 10.0.1.255 scope global secondary eth3
root@r-152-VM:~# 
```

  - New Backup router
```
root@r-153-VM:~# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 16436 qdisc noqueue state UNKNOWN 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 0e:00:a9:fe:03:a9 brd ff:ff:ff:ff:ff:ff
    inet 169.254.3.169/16 brd 169.254.255.255 scope global eth0
3: eth1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN qlen 1000
    link/ether 06:3b:ac:00:00:2d brd ff:ff:ff:ff:ff:ff
    inet 192.168.23.55/24 brd 192.168.23.255 scope global eth1
    inet 192.168.23.56/24 brd 192.168.23.255 scope global secondary eth1
4: eth2: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN qlen 1000
    link/ether 06:0a:6a:00:00:66 brd ff:ff:ff:ff:ff:ff
    inet 192.168.23.100/24 brd 192.168.23.255 scope global eth2
5: eth3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 02:00:5a:b8:00:0b brd ff:ff:ff:ff:ff:ff
    inet 10.0.1.25/24 brd 10.0.1.255 scope global eth3
root@r-153-VM:~#
```

* Fail over
  - New Master router
```
root@r-153-VM:~# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 16436 qdisc noqueue state UNKNOWN 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 0e:00:a9:fe:03:a9 brd ff:ff:ff:ff:ff:ff
    inet 169.254.3.169/16 brd 169.254.255.255 scope global eth0
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 06:3b:ac:00:00:2d brd ff:ff:ff:ff:ff:ff
    inet 192.168.23.55/24 brd 192.168.23.255 scope global eth1
    inet 192.168.23.56/24 brd 192.168.23.255 scope global secondary eth1
4: eth2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 06:0a:6a:00:00:66 brd ff:ff:ff:ff:ff:ff
    inet 192.168.23.100/24 brd 192.168.23.255 scope global eth2
5: eth3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 02:00:5a:b8:00:0b brd ff:ff:ff:ff:ff:ff
    inet 10.0.1.25/24 brd 10.0.1.255 scope global eth3
    inet 10.0.1.1/24 brd 10.0.1.255 scope global secondary eth3
root@r-153-VM:~#
```

  - New Backup router
```
root@r-152-VM:~# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 16436 qdisc noqueue state UNKNOWN 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 0e:00:a9:fe:01:b5 brd ff:ff:ff:ff:ff:ff
    inet 169.254.1.181/16 brd 169.254.255.255 scope global eth0
3: eth1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN qlen 1000
    link/ether 06:3b:ac:00:00:2d brd ff:ff:ff:ff:ff:ff
    inet 192.168.23.56/24 brd 192.168.23.255 scope global eth1
    inet 192.168.23.55/24 brd 192.168.23.255 scope global secondary eth1
4: eth2: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN qlen 1000
    link/ether 06:ad:f6:00:00:66 brd ff:ff:ff:ff:ff:ff
    inet 192.168.23.100/24 brd 192.168.23.255 scope global eth2
5: eth3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 02:00:61:08:00:0a brd ff:ff:ff:ff:ff:ff
    inet 10.0.1.233/24 brd 10.0.1.255 scope global eth3
root@r-152-VM:~#
```

* Fail back
  - New Master router
```
root@r-152-VM:~# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 16436 qdisc noqueue state UNKNOWN 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 0e:00:a9:fe:01:b5 brd ff:ff:ff:ff:ff:ff
    inet 169.254.1.181/16 brd 169.254.255.255 scope global eth0
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 06:3b:ac:00:00:2d brd ff:ff:ff:ff:ff:ff
    inet 192.168.23.56/24 brd 192.168.23.255 scope global eth1
    inet 192.168.23.55/24 brd 192.168.23.255 scope global secondary eth1
4: eth2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 06:ad:f6:00:00:66 brd ff:ff:ff:ff:ff:ff
    inet 192.168.23.100/24 brd 192.168.23.255 scope global eth2
5: eth3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 02:00:61:08:00:0a brd ff:ff:ff:ff:ff:ff
    inet 10.0.1.233/24 brd 10.0.1.255 scope global eth3
    inet 10.0.1.1/24 brd 10.0.1.255 scope global secondary eth3
root@r-152-VM:~# 
```

  - New Backup router
```
root@r-153-VM:~# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 16436 qdisc noqueue state UNKNOWN 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 0e:00:a9:fe:01:c4 brd ff:ff:ff:ff:ff:ff
    inet 169.254.1.196/16 brd 169.254.255.255 scope global eth0
3: eth1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN qlen 1000
    link/ether 06:3b:ac:00:00:2d brd ff:ff:ff:ff:ff:ff
    inet 192.168.23.56/24 brd 192.168.23.255 scope global eth1
    inet 192.168.23.55/24 brd 192.168.23.255 scope global secondary eth1
4: eth2: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN qlen 1000
    link/ether 06:0a:6a:00:00:66 brd ff:ff:ff:ff:ff:ff
    inet 192.168.23.100/24 brd 192.168.23.255 scope global eth2
5: eth3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 02:00:5a:b8:00:0b brd ff:ff:ff:ff:ff:ff
    inet 10.0.1.25/24 brd 10.0.1.255 scope global eth3
root@r-153-VM:~#
```

**Comment by wilderrodrigues** [comment]
Ping @remibergsma @borisroman @bheuvel @miguelaferreira 

We test this PR against NSX this morning and all is working fine. We had an issue due to the revert of the NSX PR (commit ID f66a857db6e03982418a039cba0040bd5989ffdf). The revert was not  part of MCCloud, that's why we did not face the same issue there.

@borisroman and I tested this PR as follows:

1. Created 1 rVPC + 1 Tier + 1 ACL + 2 ACL items + 1 VM + 1 IP + 1 PF + 1 Pvt GW
2. Stop Master router
    - Observe that the Backup router becomes Master
    - Public and Private GW interfaces are UP 
    - SSH into the VM via the Pub IP
3.  Start the stopped router
    - Observe that the Backup router becomes Backup
    - Public and Private GW interfaces are DOWN
4. Repeat steps 2 and 3
5. Restart rVPC with clean-up
6. Check the routers
    - We should have a Master/Backup pair
    - SSH into the Vm via Pub IP
7. Repeat steps 2, 5 and 6

Cheers,
Wilder and Boris

**Comment by wilderrodrigues** [comment]
Ping @borisroman @bheuvel @remibergsma 

Could we get this one, and the other 3 PRs in Xen, KVM and Client merged?

It has been extremely tested and is the fixes have been merged against MCCloud and are running on Beta-NL2.

Cheers,
Wilder

**Pull request merged**
