### PR TITLE
Use MariaDB connector for database access

### PR DESCRIPTION
**Pull request by miguelaferreira**

### CODE REVIEW

**Comment by miguelaferreira** [comment]
This PR builds on top of #110, please merge that one first

**Comment by wilderrodrigues** [comment]
go build

**Comment by wilderrodrigues** [comment]
go build

**Comment by miguelaferreira** [comment]
@wilderrodrigues it won't work yet. I'm running the job that updates the tracking repo, then we need to build master and push to nexus before this one will work.

**Comment by miguelaferreira** [comment]
go build

**Comment by miguelaferreira** [comment]
go build

**Comment by miguelaferreira** [comment]
ping @wilderrodrigues  @bheuvel

**Pull request merged**
