### PR TITLE
Remove GloboDNS plugin.

### PR DESCRIPTION
**Pull request by borisroman**
Integration tests succeeded: https://beta-jenkins.mcc.schubergphilis.com/job/cosmic/job/0002-tracking-repo-branch-build/140/

Ping @miguelaferreira @bheuvel

Merge together with: https://github.com/MissionCriticalCloud/cosmic-client/pull/62

### CODE REVIEW

**Comment by miguelaferreira** [comment]
Running integration tests again because the PR changed: https://beta-jenkins.mcc.schubergphilis.com/job/cosmic/job/0002-tracking-repo-branch-build/146/

**Comment by bheuvel** [comment]
Running integration tests again, now inculding the latest KVM repo/branch which includes the required fixes for running on OVS, which the slaves are:
https://beta-jenkins.mcc.schubergphilis.com/job/cosmic/job/0002-tracking-repo-branch-build/149/

**Comment by borisroman** [comment]
Thanks @bheuvel, I was just about to rebase with master.

**Comment by remibergsma** [comment]
Green tests!
screen shot 2016-06-11 at 14 14 07

**Pull request merged**
