### PR TITLE
Make MASTER detection for RVR similar to RVPC

### PR DESCRIPTION
**Pull request by bheuvel**

### CODE REVIEW

**Comment by wilderrodrigues** [comment]
go build

**Comment by wilderrodrigues** [comment]
go build

**Comment by wilderrodrigues** [comment]
Talked to @bheuvel and he confirmed he tested this.

**Comment by bheuvel** [comment]
```
Test redundant router internals ...
=== TestName: test_01_isolate_network_FW_PF_default_routes_egress_true | Status : SUCCESS ===
ok
Test redundant router internals ... === TestName: test_02_isolate_network_FW_PF_default_routes_egress_false | Status : SUCCESS ===
ok
Test redundant router internals ... === TestName: test_01_RVR_Network_FW_PF_SSH_default_routes_egress_true | Status : SUCCESS ===
ok
Test redundant router internals ... === TestName: test_02_RVR_Network_FW_PF_SSH_default_routes_egress_false | Status : SUCCESS ===
ok
Test redundant router internals ... === TestName: test_03_RVR_Network_check_router_state | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 5 tests in 2331.672s

OK
```

**Pull request merged**
