### PR TITLE
Guest network RVR is on eth2

### PR DESCRIPTION
**Pull request by bheuvel**
```
[root@cs1 smoke]# cat /tmp//MarvinLogs/test_routers_network_ops_W7IGSZ/results.txt
Test redundant router internals ... === TestName: test_01_isolate_network_FW_PF_default_routes_egress_true | Status : SUCCESS ===
ok
Test redundant router internals ... === TestName: test_02_isolate_network_FW_PF_default_routes_egress_false | Status : SUCCESS ===
ok
Test redundant router internals ... === TestName: test_01_RVR_Network_FW_PF_SSH_default_routes_egress_true | Status : SUCCESS ===
ok
Test redundant router internals ... === TestName: test_02_RVR_Network_FW_PF_SSH_default_routes_egress_false | Status : SUCCESS ===
ok
Test redundant router internals ... === TestName: test_03_RVR_Network_check_router_state | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 5 tests in 2280.219s

OK
```

### CODE REVIEW

**Comment by remibergsma** [comment]
@bheuvel @wilderrodrigues Fix looks good, it regressed somewhere.

Was also fixed here:
https://github.com/schubergphilis/MCCloud/commit/5ea3077961217116c84a8e95de5506a49388e3e2

Part of this PR:
https://github.com/schubergphilis/MCCloud/pull/3

**Comment by wilderrodrigues** [comment]
@bheuvel @remibergsma 

Looking at the code, we still have to fix the checkrouter.sh and the STATE_COMMANDS in the CsHelper.py.

That can be done in another PR, though.

Will you pick it up, @bheuvel ? If so, we can proceed and merge this one.

**Comment by bheuvel** [comment]
For the exact details I can re-check, but the MASTER actually has 2 ip-addresses on the guest network, and BACKUP not.
So doing a grep/count which results in 2, actually correctly determines the MASTER.

But if you like, I can "correct" the check that it checks if the public interface is UP or not (like with rVPC).
So it works now, but I can also easily "correct" it, make it more similar to the rVPC code.

@wilderrodrigues Shall I change it (in another PR)?

**Comment by wilderrodrigues** [comment]
@bheuvel 

Yep... I would say another PR. :)

Merging this one.

Thanks!

**Pull request merged**
