### PR TITLE
First part of the Java 8 + Maven refactor

### PR DESCRIPTION
**Pull request by wilderrodrigues**
This PR makes the cosmic-core submodule Maven compliant.

### CODE REVIEW

**Comment by wilderrodrigues** [comment]
Ping @borisroman @michaelandersen @miguelaferreira @bheuvel 

I already did the following tests:

* Cleaned the Maven repository
* Built the source
* Generated and Installed RPMs
* Deployed DC
* Deployed VM on isolated network

Will now run some integration tests. Will keep you updated.

**Comment by borisroman** [comment]
go build

**Comment by miguelaferreira** [comment]
go build

**Comment by wilderrodrigues** [comment]
Ping @borisroman @miguelaferreira 

More build:

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8:24.554s
[INFO] Finished at: Mon Feb 08 18:59:30 GMT 2016
[INFO] Final Memory: 61M/376M
[INFO] ------------------------------------------------------------------------
[root@cs1 cosmic-core]#
```

**Comment by wilderrodrigues** [comment]
go build

**Comment by wilderrodrigues** [comment]
Checked the Jenkins job status and saw this:

image

The class being complained about is part of the cloud-server, which was successfully build way before that.

A local - and a bubble - build of the same branch works fine:

```
[INFO] Cosmic apidocs ..................................... SUCCESS [ 26.761 s]
[INFO] Cosmic marvin ...................................... SUCCESS [  7.847 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 07:08 min
[INFO] Finished at: 2016-02-09T11:37:20+01:00
[INFO] Final Memory: 71M/977M
[INFO] ------------------------------------------------------------------------
sbpltk1zffh04:cosmic-core wrodrigues$
```

When I checked the Workspace of the Job, I found out the directory structure is not according to the changes I introduced. Check the picture below:

image

I'm trying to understand how the build works, so please bear with me. :)

When this job -> https://beta-jenkins.mcc.schubergphilis.com/job/cosmic/job/plugin-pull-request-build-cosmic-core/2/console <- started, I saw the following:

```
11:20:41 GitHub pull request #51 of commit 46d29c68216f4ca3c879acf68bd4b7f1194691af, no merge conflicts.
```

The commit ID above is from this PR. After that, it does some other check and starts the build:

```
11:20:44 Starting build job cosmic/custom-workspace-maven-job.
11:20:44 Returning node parameter for mccd-jenkins-slave-01.csdcloud.local
11:28:05 Finished Build : #63 of Job : cosmic/custom-workspace-maven-job with status : FAILURE
```

If I go to job 63, I see that it is in fact building the commit ID of this PR, which is fine. But when I go to the workspace, I still see the same old directory structure. The POM file is also old, since it still have the old ACS source and test directories.

I'm a bit lost now and it all might sound nonsense. I will try to wipe out the workspace and see what happens.

Cheers,
Wilder

**Comment by wilderrodrigues** [comment]
I wiped the workspace and started the build again. Got the following:

image

I also noticed that although it says the commit ID from the BR is being used, afterwards if does a checkout of another commit ID, which is from the latest Master:

image

**Comment by wilderrodrigues** [comment]
Okay, it's not build the PR but Master instead.

Go to -> https://beta-jenkins.mcc.schubergphilis.com/job/cosmic/job/custom-workspace-maven-job/68/consoleFull

It says:

```
12:11:28 Started by upstream project "cosmic/plugin-pull-request-build-cosmic-core" build number 4
12:11:28 originally caused by:
12:11:28  GitHub pull request #51 of commit 46d29c68216f4ca3c879acf68bd4b7f1194691af, no merge conflicts.
```

However, when the Maven build starts, it says:


```
12:11:30 Executing Maven:  -B -f /home/jenkins/workspace/cosmic/plugin-pull-request-build-cosmic-core/pom.xml clean install -P developer
12:11:31 [INFO] Scanning for projects...
12:11:32 [WARNING] 
12:11:32 [WARNING] Some problems were encountered while building the effective model for cloud.cosmic:cloud-core:jar:5.0.0-SNAPSHOT
12:11:32 [WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-pmd-plugin is missing. @ cloud.cosmic:cloud-core:[unknown-version], /home/jenkins/workspace/cosmic/plugin-pull-request-build-cosmic-core/core/pom.xml, line 54, column 15
```

Line 54 doesn't exist in the ```cosmic-core/core/pom.xml``` under the branch that created this PR.

I'm checking the job script files and see if I can fix it.

Please, let me know if my assumptions are incorrect and I should look somewhere else.

**Comment by wilderrodrigues** [comment]
go build

**Comment by miguelaferreira** [comment]
go build

**Comment by miguelaferreira** [comment]
go build

**Pull request merged**
